version: '3'
services:
  mysql:
    image: mysql
    ports:
      - "3000:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./volumes:/var/lib/mysql

  spring-app:
    image: apims:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/messageria
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""